[version]
current = "v0.0.0-alpha"

[settings]
# Trace2Inv requires EtherScan API key to fetch the contract source code
# Users can get the API key from https://etherscan.io/myapikey
EtherScanApiKeys = ["AIIG5TBENEMJHXG8END5FXRM1N7ND3KPZI"]

# Trace2Inv requires Ethereum Archive nodes to fetch transaction trace via ``debug_traceTransaction``
# We need endpoints that support this RPC method, usually it is a paid service, we chose QuickNode for this purpose.
rpcProviders = ["https://api-ethereum-mainnet.n.dwellir.com/b4942464-de9e-42fe-bfe4-80611faa04b" ]

# We also need some other Ethereum Archive nodes to fetch other blockchain states, usually it is free, we chose Alchemy for this purpose.
ethArchives = ["https://api-ethereum-mainnet.n.dwellir.com/b4942464-de9e-42fe-bfe4-80611faa04b"]

[runtime]
# It decides how deep the logging will be
LoggingUpperBound = 6

[experiment]
# It decides the ratio of the training set
# 0.7 means 70% of the transaction history will be used for training and the rest will be used for testing
trainingSetRatio = 0.7
